#!/usr/bin/env python3
"""
快捷指令签名脚本 v2 — HubSign API
修复：showresult Text 直接用字符串，避免 iOS 17 闪退
"""
import plistlib, json, time, sys, os, argparse
from urllib.request import Request, urlopen
from urllib.error import HTTPError

HUB_SIGN_URL = "https://hubsign.routinehub.services/sign"

# --- Action 构建工具 ---

def action_gettext(text):
    return {
        "WFWorkflowActionIdentifier": "is.workflow.actions.gettext",
        "WFWorkflowActionParameters": {"WFTextActionText": text},
    }

def action_setclipboard(text):
    return {
        "WFWorkflowActionIdentifier": "is.workflow.actions.setclipboard",
        "WFWorkflowActionParameters": {"WFText": text},
    }

def action_getclipboard():
    return {
        "WFWorkflowActionIdentifier": "is.workflow.actions.getclipboard",
        "WFWorkflowActionParameters": {},
    }

def action_notification(title, body):
    return {
        "WFWorkflowActionIdentifier": "is.workflow.actions.notification",
        "WFWorkflowActionParameters": {
            "WFNotificationActionTitle": title,
            "WFNotificationActionBody": body,
        },
    }

def action_showresult(text):
    # ⚠️ Text 必须用直接字符串！嵌套 dict 导致 iOS 17 闪退
    return {
        "WFWorkflowActionIdentifier": "is.workflow.actions.showresult",
        "WFWorkflowActionParameters": {"Text": text},
    }

def action_openurl(url):
    return {
        "WFWorkflowActionIdentifier": "is.workflow.actions.openurl",
        "WFWorkflowActionParameters": {"WFInput": url, "Show-WFInput": True},
    }

def action_comment(text):
    return {
        "WFWorkflowActionIdentifier": "is.workflow.actions.comment",
        "WFWorkflowActionParameters": {"WFCommentActionText": text},
    }

# --- plist 构建 ---

def build_plist(actions, icon_color=4282601983, icon_glyph=61440):
    return {
        "WFWorkflowClientVersion": "3107.0.8.2",
        "WFWorkflowClientRelease": "22.1",
        "WFWorkflowMinimumClientVersion": 900,
        "WFWorkflowTypes": ["NCWidget", "WatchKit"],
        "WFWorkflowIcon": {
            "WFWorkflowIconStartColor": icon_color,
            "WFWorkflowIconGlyphNumber": icon_glyph,
        },
        "WFWorkflowImportQuestions": [],
        "WFWorkflowInputContentItemClasses": ["WFAppStoreAppContentItem"],
        "WFWorkflowActions": actions,
    }

# --- 签名 ---

def sign_shortcut(name, plist_dict):
    xml = plistlib.dumps(plist_dict, fmt=plistlib.FMT_XML).decode()
    payload = json.dumps({"shortcutName": name, "shortcut": xml}).encode()
    req = Request(
        HUB_SIGN_URL,
        data=payload,
        headers={
            "Content-Type": "application/json",
            "Origin": "https://routinehub.co",
            "Referer": "https://routinehub.co/",
            "User-Agent": "cherri/1.0",
        },
    )
    with urlopen(req, timeout=30) as resp:
        data = resp.read()
    if data[:4] != b"AEA1":
        raise AssertionError(f"签名失败: 收到 {data[:4]}，期望 AEA1（可能是 CF 拦截，检查 UA/Origin/Referer）")
    return data

# --- 默认 demo ---

def build_demo():
    now = time.strftime('%Y-%m-%d %H:%M:%S')
    return build_plist([
        action_comment(f"Generated by 快捷指令 Skill — {now}"),
        action_gettext(f"运行: {now}"),
        action_setclipboard(f"已复制时间: {time.strftime('%H:%M:%S')}"),
        action_notification("快捷指令测试", f"运行时间: {time.strftime('%H:%M:%S')}"),
        action_showresult(f"✅ 签名测试通过!\n\n时间: {now}\n\n支持动作:\n• getText 显示文字\n• setClipboard 复制\n• notification 通知\n• showresult 弹窗\n• openurl 打开URL"),
        action_openurl("https://www.apple.com"),
    ])

# --- CLI ---

def main():
    parser = argparse.ArgumentParser(description="快捷指令签名脚本 v2 (HubSign)")
    parser.add_argument("--name", "-n", default="Shortcut", help="快捷指令名称")
    parser.add_argument("--output", "-o", default=None, help="输出文件路径")
    parser.add_argument("--actions", "-a", default=None, help="actions JSON 文件路径")
    args = parser.parse_args()

    # 构建 plist
    if args.actions:
        with open(args.actions, "r", encoding="utf-8") as f:
            actions = json.load(f)
        plist = build_plist(actions)
    else:
        plist = build_demo()

    # 签名
    print(f"🔏 正在签名: {args.name}")
    print(f"   API: {HUB_SIGN_URL}")
    print(f"   UA: cherri/1.0")
    data = sign_shortcut(args.name, plist)

    # 保存
    out = args.output or f"{args.name}.shortcut"
    with open(out, "wb") as f:
        f.write(data)
    print(f"✅ {len(data)} bytes → {out}")
    print(f"   Magic: {data[:4].hex().upper()} (AEA1 ✓)")

if __name__ == "__main__":
    main()
