# 试试双拼 https://apps.apple.com/us/app/id1613019131
# QX配置 - 直接使用 RevenueCat 通杀脚本

[MITM]
hostname = api.rc-backup.com, *.revenuecat.com

[rewrite_local]
^https?:\/\/api\.rc-backup\.com\/v1\/subscribers\/ url script-response-body https://raw.githubusercontent.com/7452323/QuantumultX/main/script/RevenueCat.js
^https?:\/\/api\.revenuecat\.com\/(v[12]\/)?(receipts|subscribers\/[^?#]+) url script-response-body https://raw.githubusercontent.com/7452323/QuantumultX/main/script/RevenueCat.js
